[package]
name = "chaos_communicator"
version = "0.1.0"
edition = "2024"
authors = ["Ólafur Þór Gunnarsson <olinord@gmail.com>"]

[dependencies]
crossbeam-channel = "0.8.4"

[dev-dependencies]
criterion = "0.7"

[[bench]]
name = "message_bench"
harness = false